### ISSUE TITLE
Snuba Issue startup

### ISSUE THREAD

**Issue by haarchri** [getsentry/snuba#956]
Hello,

we will instll sentry in an openshift environment but we have trouble with sentry-snuba-api 
startup log:

Image: getsentry/snuba:fdcc3229b24b659a48b4934e4ffc0ccaa6364a37

```
+ '[' a = - ']'
--
  | + snuba api --help
  | + set -- snuba api
  | + set gosu snuba snuba api
  | + exec gosu snuba snuba api
  | error: failed switching to "snuba": operation not permitted
```

any ideas ?

**Comment by rmohta** [comment]
When running in Openshift, configure Openshift Security Context Constraints (SCC) such that the service-account for the pod can use *anyuid* profile.

Something like below. And then use *my-sa* in pod template for serviceAccountName

`oc adm policy add-scc-to-user -n namespace anyuid -z my-sa`

**Comment by sag1** [comment]
In many Organization, we can't configure Openshift Security Context Constraints (SCC) as it needs more privileges and it's not the way to run containers on Openshift. Normally Openshift assigns randomUID to the user while running. More and more the specification are based on conatiners, why don't you change it ?

**Comment by rmohta** [comment]
Depending on the Openshift version and access to SCC, can you ensure container starts with a valid uid (k8s securiityContext section in pod template I think)?

**Comment by sag1** [comment]
In my company, this one is restricted oc adm policy add-scc-to-user -n namespace anyuid -z my-sa

**Comment by mic4ael** [comment]
I would say this is a limitation since as others mentioned already `oc adm policy` might not be available to plain Openshift users. What would be required to run `snuba api` as a random UID? Some `chown`s on directories used by `snuba`?

**Comment by cortopy** [comment]
I really don't understand why the default user of snuba is root. It's my understanding that the entrypoint merely switches to the user snuba.

This is how I fixed it in the snuba deployment:

```yaml
        - name: sentry-snuba
          image: "getsentry/snuba:21.3.0"
          imagePullPolicy: IfNotPresent
          command: ["snuba", "api"]
          securityContext:
            privileged: false
            runAsUser: 999
```

This starts the container with user snuba (999) so no sudo required, runs command "snuba api" and overrides the entrypoint
